image: node:lts

create-pages:
  pages:
    publish: storybook-static
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  before_script:
    - npm install -g pnpm
    - pnpm install --frozen-lockfile  # same as "npm ci"
  script:
    - pnpm run build-storybook
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .pnpm-store
